# pre-commit package installation is necessary to use pre-commit.
# $ pip install pre-commit
# $ pre-commit install

default_language_version:
  python: python3

repos:
  # Args are based on setup.cfg.
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.4
    hooks:
      - id: ruff-check
        args: [ --fix ]
      - id: ruff-format
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.16.0
    hooks:
    - id: mypy
      additional_dependencies: [
        "alembic>=1.5.0",
        "colorlog",
        "numpy",
        "packaging>=20.0",
        "sqlalchemy>=1.3.0",
        "tqdm",
        "PyYAML",
        "mypy_boto3_s3",
        "types-PyYAML",
        "types-redis",
        "types-setuptools",
        "types-tqdm",
        "typing_extensions>=3.10.0.0",
        "types-protobuf",
      ]
      exclude: docs|tutorial|optuna/storages/_rdb/alembic|optuna/storages/_grpc/auto_generated
      args: [
        --warn-unused-configs,
        --disallow-untyped-calls,
        --disallow-untyped-defs,
        --disallow-incomplete-defs,
        --check-untyped-defs,
        --no-implicit-optional,
        --warn-redundant-casts,
        --strict-equality,
        --extra-checks,
        --no-implicit-reexport,
        --ignore-missing-imports,
      ]
