name: Publish distributions to TestPyPI and PyPI

# Only activate if the v* tag is pushed.
on:
  push:
    tags:
    - v*

jobs:
  build-n-publish:
    name: Build and publish Python distributions to TestPyPI and PyPI
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: Install twine
      run: >-
        python -m pip install -U twine

    - name: Build a tar ball
      run: >-
        python setup.py sdist

    - name: Verify the distributions
      run: twine check dist/*

    - name: Publish distribution to Test PyPI
      # The following upload action cannot be executed in the forked repository.
      if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags')  && github.repository == 'optuna/optuna'
      uses: pypa/gh-action-pypi-publish@v1.1.0
      with:
        user: __token__
        password: ${{ secrets.test_pypi_password }}
        repository_url: https://test.pypi.org/legacy/

    - name: Publish distribution to PyPI
      # Do not upload the package from forked repository.
      if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags')  && github.repository == 'optuna/optuna'
      uses: pypa/gh-action-pypi-publish@v1.1.0
      with:
        user: __token__
        password: ${{ secrets.pypi_password }}
