name: Speed benchmarks

on:
  schedule:
    - cron: '0 23 * * SUN-THU'

jobs:
  speed-benchmarks:
    runs-on: ubuntu-latest

    # Not intended for forks.
    if: github.repository == 'optuna/optuna'

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Python3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Setup cache
      uses: actions/cache@v2
      env:
        cache-name: speed-benchmarks
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-3.9-${{ env.cache-name }}-${{ hashFiles('**/setup.py') }}-v1
        restore-keys: |
          ${{ runner.os }}-3.9-${{ env.cache-name }}-${{ hashFiles('**/setup.py') }}

    - name: Install
      run: |
        python -m pip install --upgrade pip
        pip install --use-deprecated=legacy-resolver --progress-bar off -U setuptools

        # Install minimal dependencies and confirm that `import optuna` is successful.
        pip install --use-deprecated=legacy-resolver --progress-bar off .
        python -c 'import optuna'
        optuna --version

        pip install --use-deprecated=legacy-resolver --progress-bar off .[benchmark]
        asv machine --yes

    - name: Speed benchmarks
      run: |
        asv run
