name: Sphinx

on:
  push:
    branches:
      - master
  pull_request: {}

jobs:
  documentation:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2

    - uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Get date for cache
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

    - name: Pip cache
      uses: actions/cache@v2
      env:
        cache-name: pip-documentation
      with:
        path: ~/.cache/pip
        key: py3.8-${{ env.cache-name }}-${{ hashFiles('**/setup.py') }}
        restore-keys: |
          py3.8-${{ env.cache-name }}-${{ hashFiles('**/setup.py') }}

    - name: Sphinx Gallery Cache
      uses: actions/cache@v2
      env:
        cache-name: sphx-glry-documentation
      with:
        path: |
          tutorial/MNIST
          tutorial/FashionMNIST
          docs/source/tutorial
        key: py3.8-${{ steps.date.outputs.date }}-${{ env.cache-name }}-${{ hashFiles('tutorial/**/README.rst') }}

    - name: Install Dependencies
      run: |
        python -m pip install -U pip
        pip install --progress-bar off -U .[document,doctest] -f https://download.pytorch.org/whl/torch_stable.html

    - name: Build Document
      run: |
        cd docs
        make html
        cd ../

    - uses: actions/upload-artifact@v2
      with:
        name: built-document
        path: docs/build

  doctest:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2

    - uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Pip cache
      uses: actions/cache@v2
      env:
        cache-name: pip-doctest
      with:
        path: ~/.cache/pip
        key: py3.8-${{ env.cache-name }}-${{ hashFiles('**/setup.py') }}
        restore-keys: |
          py3.8-${{ env.cache-name }}-${{ hashFiles('**/setup.py') }}

    - name: Sphinx Gallery Cache
      uses: actions/cache@v2
      env:
        cache-name: sphx-glry-doctest
      with:
        path: |
          tutorial/MNIST
          tutorial/FashionMNIST
          docs/source/tutorial
        key: py3.8-${{ steps.date.outputs.date }}-${{ env.cache-name }}-${{ hashFiles('tutorial/**/README.rst') }}

    - name: Install Dependencies
      run: |
        python -m pip install -U pip
        pip install --progress-bar off -U .[document,doctest] -f https://download.pytorch.org/whl/torch_stable.html

    - name: Run Doctest
      run: |
        cd docs
        make doctest
