name: Publish distributions to TestPyPI

# Only activate on the master push.
on:
  push:
    branches:
      - master

jobs:
  build-n-publish:
    name: Build and publish Python distributions to TestPyPI
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: Install twine
      run: >-
        python -m pip install -U twine wheel

    - name: Build a tar ball
      run: |
        python setup.py sdist
        python setup.py bdist_wheel

    - name: Verify the distributions
      run: twine check dist/*

    - name: Publish distribution to Test PyPI
      # The following upload action cannot be executed in the forked repository.
      if: github.repository == 'optuna/optuna'
      uses: pypa/gh-action-pypi-publish@v1.1.0
      with:
        user: __token__
        password: ${{ secrets.test_pypi_password }}
        repository_url: https://test.pypi.org/legacy/
